apiVersion: v1
kind: Service
metadata:
  name: llm-{{ .Values.modelName }}-{{ .Values.target }}-svc
  namespace: rse
  labels:
    app.kubernetes.io/name: llm-{{ .Values.modelName }}-{{ .Values.target }}-svc
    app.kubernetes.io/component: server
spec:
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
  selector:
    app.kubernetes.io/name: llm-{{ .Values.modelName }}
