apiVersion: v1
kind: Service
metadata:
  name: llm-{{ .Values.modelPath }}-svc
  namespace: {{ .Values.namespace}}
  labels:
    app.kubernetes.io/name: llm-{{ .Values.modelPath }}-svc
    app.kubernetes.io/component: server
spec:
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
      
  selector:
    app.kubernetes.io/name: llm-{{ .Values.modelPath }}
    
